apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-demo-monitor
  labels:
    app: metrics-demo-monitor
    release: test-release
spec:
  endpoints:
    - port: http-metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - otus-microservices-k8s-deployment-service-ingress-users
  selector:
    matchLabels:
      app: k8s-deployment-service-ingress-users.webapi
  
